/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  RsvpContractAbi,
  RsvpContractAbiInterface,
} from "../RsvpContractAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 5,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 6,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "enum InvalidRSVPError",
      components: [
        {
          name: "IncorrectAssetId",
          type: 0,
          typeArguments: null,
        },
        {
          name: "NotEnoughTokens",
          type: 0,
          typeArguments: null,
        },
        {
          name: "InvalidEventID",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "str[10]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 7,
      type: "struct Event",
      components: [
        {
          name: "unique_id",
          type: 8,
          typeArguments: null,
        },
        {
          name: "max_capacity",
          type: 8,
          typeArguments: null,
        },
        {
          name: "deposit",
          type: 8,
          typeArguments: null,
        },
        {
          name: "owner",
          type: 2,
          typeArguments: null,
        },
        {
          name: "name",
          type: 4,
          typeArguments: null,
        },
        {
          name: "num_of_rsvps",
          type: 8,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "capacity",
          type: 8,
          typeArguments: null,
        },
        {
          name: "price",
          type: 8,
          typeArguments: null,
        },
        {
          name: "event_name",
          type: 4,
          typeArguments: null,
        },
      ],
      name: "create_event",
      output: {
        name: "",
        type: 7,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "event_id",
          type: 8,
          typeArguments: null,
        },
      ],
      name: "get_rsvp",
      output: {
        name: "",
        type: 7,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: "event_id",
          type: 8,
          typeArguments: null,
        },
      ],
      name: "rsvp",
      output: {
        name: "",
        type: 7,
        typeArguments: null,
      },
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
  ],
};

export class RsvpContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): RsvpContractAbiInterface {
    return new Interface(_abi) as unknown as RsvpContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): RsvpContractAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as RsvpContractAbi;
  }
}
