/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RsvpContractAbi } from "./RsvpContractAbi";

export { RsvpContractAbi__factory } from "./factories/RsvpContractAbi__factory";
