/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

import type { Enum, Option } from "./common";

export type AddressInput = { value: string };

export type AddressOutput = { value: string };

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

export type EventInput = {
  unique_id: BigNumberish;
  max_capacity: BigNumberish;
  deposit: BigNumberish;
  owner: IdentityInput;
  name: string;
  num_of_rsvps: BigNumberish;
};

export type EventOutput = {
  unique_id: BN;
  max_capacity: BN;
  deposit: BN;
  owner: IdentityOutput;
  name: string;
  num_of_rsvps: BN;
};

export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;

export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;

interface RsvpContractAbiInterface extends Interface {
  functions: {
    create_event: FunctionFragment;
    rsvp: FunctionFragment;
    get_event: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create_event",
    values: [BigNumberish, BigNumberish, string]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "rsvp",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "get_event",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "create_event",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(functionFragment: "rsvp", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_event",
    data: BytesLike
  ): DecodedValue;
}

export class RsvpContractAbi extends Contract {
  interface: RsvpContractAbiInterface;
  functions: {
    create_event: InvokeFunction<
      [capacity: BigNumberish, price: BigNumberish, event_name: string],
      EventOutput
    >;

    rsvp: InvokeFunction<[event_id: BigNumberish], EventOutput>;

    get_event: InvokeFunction<[event_id: BigNumberish], EventOutput>;
  };
}
